#define ZCC_EQ                               1
#define ZCC_MULEQ                            2
#define ZCC_DIVEQ                            3
#define ZCC_MODEQ                            4
#define ZCC_ADDEQ                            5
#define ZCC_SUBEQ                            6
#define ZCC_LSHEQ                            7
#define ZCC_RSHEQ                            8
#define ZCC_ANDEQ                            9
#define ZCC_OREQ                            10
#define ZCC_XOREQ                           11
#define ZCC_URSHEQ                          12
#define ZCC_QUESTION                        13
#define ZCC_COLON                           14
#define ZCC_OROR                            15
#define ZCC_ANDAND                          16
#define ZCC_EQEQ                            17
#define ZCC_NEQ                             18
#define ZCC_APPROXEQ                        19
#define ZCC_LT                              20
#define ZCC_GT                              21
#define ZCC_LTEQ                            22
#define ZCC_GTEQ                            23
#define ZCC_LTGTEQ                          24
#define ZCC_LTEQGT                          25
#define ZCC_IS                              26
#define ZCC_DOTDOT                          27
#define ZCC_OR                              28
#define ZCC_XOR                             29
#define ZCC_AND                             30
#define ZCC_LSH                             31
#define ZCC_RSH                             32
#define ZCC_URSH                            33
#define ZCC_SUB                             34
#define ZCC_ADD                             35
#define ZCC_MUL                             36
#define ZCC_DIV                             37
#define ZCC_MOD                             38
#define ZCC_CROSSPROD                       39
#define ZCC_DOTPROD                         40
#define ZCC_POW                             41
#define ZCC_UNARY                           42
#define ZCC_ADDADD                          43
#define ZCC_SUBSUB                          44
#define ZCC_DOT                             45
#define ZCC_LPAREN                          46
#define ZCC_LBRACKET                        47
#define ZCC_SCOPE                           48
#define ZCC_EOF                             49
#define ZCC_SEMICOLON                       50
#define ZCC_COMMA                           51
#define ZCC_INCLUDE                         52
#define ZCC_EXTEND                          53
#define ZCC_CLASS                           54
#define ZCC_IDENTIFIER                      55
#define ZCC_ABSTRACT                        56
#define ZCC_FINAL                           57
#define ZCC_NATIVE                          58
#define ZCC_UI                              59
#define ZCC_PLAY                            60
#define ZCC_REPLACES                        61
#define ZCC_VERSION                         62
#define ZCC_STRCONST                        63
#define ZCC_RPAREN                          64
#define ZCC_SEALED                          65
#define ZCC_DEPRECATED                      66
#define ZCC_ACTION                          67
#define ZCC_DEFAULT                         68
#define ZCC_COLOR                           69
#define ZCC_LBRACE                          70
#define ZCC_RBRACE                          71
#define ZCC_MIXIN                           72
#define ZCC_PROPERTY                        73
#define ZCC_FLAGDEF                         74
#define ZCC_INTCONST                        75
#define ZCC_INTERNAL                        76
#define ZCC_STRUCT                          77
#define ZCC_CLEARSCOPE                      78
#define ZCC_UNSAFE                          79
#define ZCC_CONST                           80
#define ZCC_ENUM                            81
#define ZCC_STATES                          82
#define ZCC_NWS                             83
#define ZCC_STOP                            84
#define ZCC_WAIT                            85
#define ZCC_FAIL                            86
#define ZCC_LOOP                            87
#define ZCC_GOTO                            88
#define ZCC_SUPER                           89
#define ZCC_BRIGHT                          90
#define ZCC_FAST                            91
#define ZCC_SLOW                            92
#define ZCC_NODELAY                         93
#define ZCC_CANRAISE                        94
#define ZCC_OFFSET                          95
#define ZCC_LIGHT                           96
#define ZCC_SBYTE                           97
#define ZCC_BYTE                            98
#define ZCC_SHORT                           99
#define ZCC_USHORT                         100
#define ZCC_INT                            101
#define ZCC_UINT                           102
#define ZCC_BOOL                           103
#define ZCC_FLOAT                          104
#define ZCC_DOUBLE                         105
#define ZCC_VECTOR2                        106
#define ZCC_VECTOR3                        107
#define ZCC_VECTOR4                        108
#define ZCC_NAME                           109
#define ZCC_SOUND                          110
#define ZCC_STATE                          111
#define ZCC_LET                            112
#define ZCC_ATSIGN                         113
#define ZCC_READONLY                       114
#define ZCC_STRING                         115
#define ZCC_MAP                            116
#define ZCC_MAPITERATOR                    117
#define ZCC_ARRAY                          118
#define ZCC_VOID                           119
#define ZCC_UINT8                          120
#define ZCC_INT8                           121
#define ZCC_UINT16                         122
#define ZCC_INT16                          123
#define ZCC_FNTYPE                         124
#define ZCC_RBRACKET                       125
#define ZCC_STATIC                         126
#define ZCC_PRIVATE                        127
#define ZCC_PROTECTED                      128
#define ZCC_LATENT                         129
#define ZCC_META                           130
#define ZCC_TRANSIENT                      131
#define ZCC_NOROLLBACK                     132
#define ZCC_VIRTUAL                        133
#define ZCC_OVERRIDE                       134
#define ZCC_VARARG                         135
#define ZCC_VIRTUALSCOPE                   136
#define ZCC_ELLIPSIS                       137
#define ZCC_IN                             138
#define ZCC_OUT                            139
#define ZCC_OPTIONAL                       140
#define ZCC_TILDE                          141
#define ZCC_BANG                           142
#define ZCC_SIZEOF                         143
#define ZCC_ALIGNOF                        144
#define ZCC_UINTCONST                      145
#define ZCC_FLOATCONST                     146
#define ZCC_NAMECONST                      147
#define ZCC_FALSE                          148
#define ZCC_TRUE                           149
#define ZCC_NULLPTR                        150
#define ZCC_STATICCONST                    151
#define ZCC_CONTINUE                       152
#define ZCC_BREAK                          153
#define ZCC_RETURN                         154
#define ZCC_DO                             155
#define ZCC_FOR                            156
#define ZCC_FOREACH                        157
#define ZCC_WHILE                          158
#define ZCC_UNTIL                          159
#define ZCC_IF                             160
#define ZCC_ELSE                           161
#define ZCC_SWITCH                         162
#define ZCC_CASE                           163
